version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: report-postgres
    environment:
      POSTGRES_DB: moteur_rapports
      POSTGRES_USER: reportuser
      POSTGRES_PASSWORD: rodrigue
    ports:
      - "5454:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: