spring:
  datasource:
    url: jdbc:postgresql://localhost:5454/moteur_rapports
    username: reportuser
    password: rodrigue
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081