spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5454/moteur_rapports}
    username: ${DB_USERNAME:reportuser}
    password: ${DB_PASSWORD:rodrigue}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    version: openapi_3_0
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    operations-sorter: method          # trie les opérations par méthode HTTP
    tags-sorter: alpha                # trie les tags par ordre alphabétique
    display-request-duration: true    # affiche la durée des requêtes
    doc-expansion: none               # les sections sont repliées au chargement
    filter: true                      # active le champ de recherche/filtre
    show-extensions: true
    show-common-extensions: true

server:
  port: 8082

app:
  storage-path: ${STORAGE_PATH:./data/reports}
